spring.application.name=Gruhani
spring.datasource.url=jdbc:postgresql://ep-flat-band-a8e7vb1b-pooler.eastus2.azure.neon.tech/neondb?user=neondb_owner&password=npg_lU2jHEv7NIzP&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_pTqOovls5FH8
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8085}
spring.security.oauth2.client.registration.google.client-id=297151085641-hnppfnd4pmd33j8t39gjjtk9g9qo4tuq.apps.googleusercontent.com
spring.main.allow-bean-definition-overriding=true


jwt.secretKey="abhdgjgi3u27yr73yiugf3ntctylurej5cy4lriujciuhcirukycriuhkcyniuthvtyckntrlnthkcryhjn"
logging.level.org.springframework.security=DEBUG
logging.level.root= INFO
logging.level.com.example.Gruhani=DEBUG
//cloudinary
CLOUDINARY_URL=cloudinary://912139629186561:WPXNsA99gu7bYdzbdu-AMcpoEJY@dk9lq9wyt
cloudinary.cloud_name=dk9lq9wyt
cloudinary.api-key=912139629186561
cloudinary.api-secret=WPXNsA99gu7bYdzbdu-AMcpoEJY


# application.properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gruhani214@gmail.com
spring.mail.password=sivp ctpo xjzo cfaq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true






